# Generated by Django 3.2.7 on 2021-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('publish', 'PUBLISH'), ('private', 'PRIVATE')], default='DRAFT', max_length=120),
        ),
    ]
