# Generated by Django 3.2.7 on 2021-09-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft'), ('PR', 'Private')], default='DR', max_length=120),
        ),
    ]
