# Generated by Django 3.2.7 on 2021-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210922_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
