# Generated by Django 3.2.7 on 2021-09-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_publish_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
